Traceback (most recent call last):
  File "C:\Users\sayala\AppData\Roaming\Python\Python311\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\ProgramData\Anaconda3\Lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\Anaconda3\Lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\Anaconda3\Lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\Anaconda3\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\ProgramData\Anaconda3\Lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\ProgramData\Anaconda3\Lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\ProgramData\Anaconda3\Lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
site = input("Which Solar Bounty Data Prize Site do you wish to access? Enter thier unique ID number: ")
path = ''
if site:
    path = input("Where do you want to download the data to? Enter full path: ")
    if path:
        if os.path.isdir(path):
            print ("Site " + site + " time-series data to be downloaded to " + path)
        else:
            raise OSError('Path ' + path + " does not exists. Please add or cange path and restart.")

------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mStdinNotImplementedError[0m                  Traceback (most recent call last)
Cell [1;32mIn[3], line 1[0m
[1;32m----> 1[0m site [38;5;241m=[39m [38;5;28minput[39m([38;5;124m"[39m[38;5;124mWhich Solar Bounty Data Prize Site do you wish to access? Enter thier unique ID number: [39m[38;5;124m"[39m)
[0;32m      2[0m path [38;5;241m=[39m [38;5;124m'[39m[38;5;124m'[39m
[0;32m      3[0m [38;5;28;01mif[39;00m site:

File [1;32mC:\ProgramData\anaconda3\Lib\site-packages\ipykernel\kernelbase.py:1172[0m, in [0;36mKernel.raw_input[1;34m(self, prompt)[0m
[0;32m   1165[0m [38;5;250m[39m[38;5;124;03m"""Forward raw_input to frontends[39;00m
[0;32m   1166[0m 
[0;32m   1167[0m [38;5;124;03mRaises[39;00m
[0;32m   1168[0m [38;5;124;03m------[39;00m
[0;32m   1169[0m [38;5;124;03mStdinNotImplementedError if active frontend doesn't support stdin.[39;00m
[0;32m   1170[0m [38;5;124;03m"""[39;00m
[0;32m   1171[0m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m [38;5;28mself[39m[38;5;241m.[39m_allow_stdin:
[1;32m-> 1172[0m     [38;5;28;01mraise[39;00m StdinNotImplementedError(
[0;32m   1173[0m         [38;5;124m"[39m[38;5;124mraw_input was called, but this frontend does not support input requests.[39m[38;5;124m"[39m
[0;32m   1174[0m     )
[0;32m   1175[0m [38;5;28;01mreturn[39;00m [38;5;28mself[39m[38;5;241m.[39m_input_request(
[0;32m   1176[0m     [38;5;28mstr[39m(prompt),
[0;32m   1177[0m     [38;5;28mself[39m[38;5;241m.[39m_parent_ident[[38;5;124m"[39m[38;5;124mshell[39m[38;5;124m"[39m],
[0;32m   1178[0m     [38;5;28mself[39m[38;5;241m.[39mget_parent([38;5;124m"[39m[38;5;124mshell[39m[38;5;124m"[39m),
[0;32m   1179[0m     password[38;5;241m=[39m[38;5;28;01mFalse[39;00m,
[0;32m   1180[0m )

[1;31mStdinNotImplementedError[0m: raw_input was called, but this frontend does not support input requests.
StdinNotImplementedError: raw_input was called, but this frontend does not support input requests.

